# Lab02 - numpy
#### Name: Matt McLaughlin 
#### Class: CSCI 349 - Intro to Data Mining 
#### Semester: 2020SP 
#### Instructor: Brian King

In [1]:
import sys
import numpy as np

#### 1) [P] Create an 52500 x 75 matrix of zeros, stored as X. Then print out the shape of the matrix, the base data type, the individual item size in the array, and the total size of the array in bytes (as an integer). Also, print out the total size in megabytes with 3 places of significance.

In [2]:
x = np.zeros((52500, 75))
print("Shape: " + str(x.shape))
print("Base data type: " + str( x.dtype ) )
print("Individual item size: " + str( x.itemsize ) )
print("Total size of array (bytes): " + str( x.size * x.itemsize ) )
sizeMB = (x.size * x.itemsize) / 1000000
print("Total size of array (megabytes): " + "{:.3f}".format(sizeMB))

Shape: (52500, 75)
Base data type: float64
Individual item size: 8
Total size of array (bytes): 31500000
Total size of array (megabytes): 31.500


#### 2) [P] Resize X to have the same number of elements, but with 100 rows. Show the shape. Show the number of bytes (which should be the same as the previous answer)

In [3]:
newCol = int(x.size / 100) #number of columns = # elements / # of rows
x = np.resize(x, (100, newCol))
print("Shape: " + str(x.shape))
print("Total size of array (bytes): " + str( x.size * x.itemsize ) )

Shape: (100, 39375)
Total size of array (bytes): 31500000


#### 3) [P] Redo #1, but use a base datatype of 16-bit integers.

In [4]:
x = np.zeros((52500, 75), dtype='int16')
print("Shape: " + str(x.shape))
print("Base data type: " + str( x.dtype ) )
print("Individual item size: " + str( x.itemsize ) )
print("Total size of array (bytes): " + str( x.size * x.itemsize ) )
sizeMB = (x.size * x.itemsize) / 1000000
print("Total size of array (megabytes): " + "{:.3f}".format(sizeMB))

Shape: (52500, 75)
Base data type: int16
Individual item size: 2
Total size of array (bytes): 7875000
Total size of array (megabytes): 7.875


#### 4) [P] How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.

In [5]:
print("Number of dimensions: " + str(x.ndim) )

Number of dimensions: 2


#### 5) [P] Enter the following list in your cell:
#### str_nums = ['2.14', '-9.3', '42']
#### Convert this to a numpy array named X. What is the base type?
#### Then, convert X to an array of single precision floating point numbers. (HINT: use astype)
#### Let's assume you have two week's worth of quiz scores. Quizzes are out of 10 points, and are given every day.
#### Enter the following in your cell:
#### days = ["Mon","Tue","Wed","Thu","Fri"]
#### scores_1 = [9.5, 8.75, 8, 10, 7.75]
#### scores_2 = [9, 8, 10, 8.75, 7.25]
#### The array scores_1 represents quiz scores from week 1, and scores_2 is week 2. The days array will be used for data selection purposes.

In [6]:
str_nums = ['2.14', '-9.3', '42']

x = np.array(str_nums)
print("Base type: " + str(x.dtype) )

x = x.astype(np.single) #np.single is a "Platform-defined single precision float"

days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]

Base type: <U4


#### 6) [P] Create a numpy array called scores, that has scores_1 as the first row and scores_2 as the second row, using np.concatenate. Then, change days into a np.array from the list days. Verify the shape of scores and days.

In [33]:
scores_1 = np.array(scores_1)
scores_2 = np.array(scores_2)
scores = np.concatenate((scores_1, scores_2)).reshape(2,5)
#This is returning 1x10 instead of 2x5
#Can't figure it our for the life of me
#Manual fix with .reshape(2,5)

days = np.array(days)
print(scores)
print("Shape of scores: " + str(scores.shape))
print("Shape of days: " + str(days.shape))

[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
Shape of scores: (2, 5)
Shape of days: (5,)


#### 7) [P] Repeat the previous problem, but repeat it with np.vstack. The array should be identical.

In [8]:
scores_1 = np.array(scores_1)
scores_2 = np.array(scores_2)
scores = np.vstack( (scores_1, scores_2) )

days = np.array(days)

print(scores)
print("Shape of scores: " + str(scores.shape))
print("Shape of days: " + str(days.shape))

[[ 9.5   8.75  8.   10.    7.75]
 [ 9.    8.   10.    8.75  7.25]]
Shape of scores: (2, 5)
Shape of days: (5,)


#### 8) [M] Compare the result of the expression days == "Fri" if the variable days was a Python list, vs. days being a numpy array. What is the difference? In general, how does numpy deal with standard comparison operators?

#### np.equal(x1, x2) (or just ==) compares for element-wise equality and returns a list of booleans. What is compared are values, not types. So an int (1) and an array of length one can evaluate as True. https://docs.scipy.org/doc/numpy-1.11.0/reference/generated/numpy.equal.html#numpy.equal 

#### Python checking for equality will return a single boolean. 

#### 9) [P] Select the scores that fell on Monday

In [9]:
#Done, but I feel like I didn't do it correctly
for i in range(days.size):
    if days[i] == "Mon":
        scoresOnMonday = np.array([])
        for j in range( scores.shape[0] ):
            scoresOnMonday = np.concatenate((scoresOnMonday, scores[j][i]), axis=None )

print(scoresOnMonday)

[9.5 9. ]


#### 10) [P] Select all of the scores that are NOT on Monday (Hint – look up the ~ operator)

In [10]:
scoresNotOnMonday = np.array([])
for i in range(days.size):
    if days[i] != "Mon":
        for j in range( scores.shape[0] ):
            scoresNotOnMonday = np.append(scoresNotOnMonday, scores[j][i] )

print(scoresNotOnMonday)

[ 8.75  8.    8.   10.   10.    8.75  7.75  7.25]


#### 11) [P] Select the scores that were on Tuesday or Thursday

In [11]:
scoresTTh = np.array([])
for i in range(days.size):
    if days[i] == "Tue" or days[i] == "Thu":
        for j in range( scores.shape[0] ):
            scoresTTh = np.append(scoresTTh, scores[j][i] )

print(scoresTTh)

[ 8.75  8.   10.    8.75]


#### 12) [P] Show the minimum and maximum scores for the entire array of scores

In [12]:
minimum = np.amin(scores)
maximum = np.amax(scores)
print("Min: " + str(minimum))
print("Max: " + str(maximum))

Min: 7.25
Max: 10.0


#### 13) [P] Show the minimum scores for each week as a new array with the same dimensions (hint – use the keepdims parameter).

In [13]:
#This is weird to me- by my understanding axis=0 should have it go by rows, not axis=1
minArr = np.amin(scores, axis=1, keepdims=True)

print("Min: " + str(minArr))

Min: [[7.75]
 [7.25]]


#### 14) [P] Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to index days.)

In [14]:
maxDayArr = np.argmax(scores, axis=1)
maxWk1 = days[maxDayArr[0]]
maxWk2 = days[maxDayArr[1]]
print("Max score week 1 occured on: " + maxWk1)
print("Max score week 2 occured on: " + maxWk2)

Max score week 1 occured on: Thu
Max score week 2 occured on: Wed


#### 15) [P] Report the mean of the scores of each week

In [15]:
mean = np.mean(scores, axis=1)
print("Mean week 1: " + str(mean[0]))
print("Mean week 2: " + str(mean[1]))

Mean week 1: 8.8
Mean week 2: 8.6


#### 16) [P] Suppose the lowest score was dropped from each week. Report the mean of each week, but without the minimum score for that week.

In [16]:
minDayArr = np.argmin(scores, axis=1)
newScores = np.delete(scores, minDayArr, axis=1) #Don't forget np.delete takes INDICES
newMean = np.mean(newScores, axis=1)
print("Mean week 1: " + str(newMean[0]))
print("Mean week 2: " + str(newMean[1]))

Mean week 1: 9.0625
Mean week 2: 8.9375


#### 17) [P] Convert the scores to fall on a scale from 0-100 instead of 0-10. Show the result.

In [17]:
scores = scores * 10 #Multiplying element-wise is intuitive
print(scores)

[[ 95.   87.5  80.  100.   77.5]
 [ 90.   80.  100.   87.5  72.5]]


#### Copy and paste this code into a cell:
#### np.random.seed(1234)
#### X = np.random.randint(1,100,50).reshape((10,5))
#### X
#### You may use standard selection techniques with integers and slicing for the following exercises


In [18]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X

array([[48, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

#### 18) [P] Select the first row of X

In [19]:
firstRow = X[0]
print(firstRow)

[48 84 39 54 77]


#### 19) [P] Select the last column of X

In [20]:
lastCol = X[:,-1]
print(lastCol)

[77 27 59 48 39 81 66 61 14 32]


#### 20) [P] Select the first AND last column of X

In [21]:
firstLastCol = X[:,[0,-1]]
print(firstLastCol)

[[48 77]
 [25 27]
 [31 59]
 [93 48]
 [51 39]
 [68 81]
 [ 4 66]
 [76 61]
 [47 14]
 [97 32]]


#### 21) [P] Select every other row of X

In [22]:
#i:j:k  - i is start, j is end, k is step. So this is start at beginning, don't end, step by 2
evOthRow = X[0::2]
print(evOthRow)

[[48 84 39 54 77]
 [31 44 31 27 59]
 [51 77 38 35 39]
 [ 4  3 20 13 66]
 [47 29 82 88 14]]


#### 22) [P] Show the transpose of X, but don't change X itself

In [23]:
transposedX = np.transpose(X)
print(transposedX)

[[48 25 31 93 51 68  4 76 47 97]
 [84 16 44 70 77 12  3 82 29 13]
 [39 50 31 81 38  1 20 15 82 70]
 [54 24 27 74 35 76 13 72 88 96]
 [77 27 59 48 39 81 66 61 14 32]]


#### 23) [P] Select the first column of X and set the result to Y.

In [24]:
Y = X[:,0]
print(Y)

[48 25 31 93 51 68  4 76 47 97]


#### 24) [P] Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change?

In [25]:
Y[0] = Y[0] + 1
print("Y[0] = " + str(Y[0]))
print("X[0][0] = " + str(X[0][0]))
#Both values changed

Y[0] = 49
X[0][0] = 49


#### 25) [P] Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y and ensure that the corresponding value of X did not change.

In [26]:
Y = np.copy(X[:,0])
Y[0] = Y[0] + 1
print("Y[0] = " + str(Y[0]))
print("X[0][0] = " + str(X[0][0]))

Y[0] = 50
X[0][0] = 49


#### 26) [P] Create an array that contains the sequence of numbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10 matrix, stored as X.

In [27]:
#When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases.
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
X = np.arange(0,10,.1).reshape(10,10)
print(X)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
 [1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9]
 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
 [3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
 [4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
 [5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
 [6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9]
 [7.  7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]
 [8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9]
 [9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]]


#### 27) [P] Set the RNG seed to 1234. Then create an array X of 100 uniformly distributed numbers, with all values between 1.0 and 10.0. Then, show the mean, the median, the minimum and maximum values of X.

In [28]:
np.random.seed(seed=1234)
X = np.linspace(1,10,100)
mean = np.mean(X)
median = np.median(X)
minVal = np.amin(X)
maxVal = np.amax(X)

print("Mean: " + str(mean))
print("Median: " + str(median))
print("Min: " + str(minVal))
print("Max: " + str(maxVal))

Mean: 5.5
Median: 5.5
Min: 1.0
Max: 10.0


#### 28) [M] Define what is meant by a normal distribution. What are the parameters of a normal distribution?

##### A normal distribution is an arrangement of a data set in which most values cluster in the middle of the range and the rest taper off symmetrically toward either extreme.
##### https://whatis.techtarget.com/definition/normal-distribution

##### The parameters of a normal distribution is the mean and the standard deviation. 
##### http://onlinestatbook.com/2/normal_distribution/intro.html

#### 29) [M] In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?

##### As the number of samples increase our data will approach the theoretical model, meaning it will smooth out and resemble the normal distribution.

#### 30) [P] Write a function called test_normal_dist. The purpose of this function is to evaluate the law of largenumbers. It should have four parameters:
#### mu = mean of distribution
#### sd = standard deviation
#### vec_length = length of the vector to generate randomly from a normal distribution, with mu and sd as parameters
#### num_trials = number of times to repeat the experiment
#### The function should behave as follows. First, initialize the seed value to 1234, before your loop. Then, loop for num_trials, generating vec_length numbers from a normal distribution. Compute the mean of that vector, then compute its deviation (absolute value of the observed mean - expected mean). This should be repeated for all trials, and then return the average deviation over all trials.

In [29]:
def test_normal_dist(mu, sd, vec_length, num_trials):
    np.random.seed(seed=1234)
    totalDev = 0
    for i in range(num_trials):
        normDistr = np.random.normal(mu, sd, vec_length)
        meanOfDist = np.mean(normDistr)
        deviation = np.absolute(meanOfDist - mu)
        totalDev += deviation
    avgDev = totalDev / num_trials
    return avgDev

#### 31) [P] Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two dimensions. the first being the vector length, and the second being the average deviation resulting from your test_normal_dist function.

In [30]:
vLenArr = np.array([10, 100, 1000, 10000, 100000])
resultArr = np.array([1, 2])
for i in vLenArr:
    newEntry = np.array( [i, test_normal_dist(0,1,i,100)] )
    resultArr = np.vstack((resultArr, newEntry))

resultArr = np.delete(resultArr, 0, 0)
print(resultArr)

[[1.00000000e+01 2.38620418e-01]
 [1.00000000e+02 8.09625326e-02]
 [1.00000000e+03 2.22900007e-02]
 [1.00000000e+04 7.94419424e-03]
 [1.00000000e+05 2.44350610e-03]]
